# Python CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3

    working_directory: ~/repo

    steps:
      # Checkout code
      - checkout
      # Update and initialize submodules
      - run: git submodule sync
      - run: git submodule update --init

      # Create folder for test results.
      - run:
          name: Create test result folder
          command: |
            mkdir test-reports

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "PyDynamic/requirements.txt" }}
              {{ checksum "agentMet4FoF/requirements.txt" }}
            # Fallback to using the latest cache if no exact match is found.
            - v1-dependencies-

      # Install dependencies and Codecov reporter if necessary.
      - run:
         name: Install dependencies
         command: |
           python3 -m venv venv
           . venv/bin/activate
           pip install -r agentMet4FoF/requirements.txt
           pip install -r PyDynamic/requirements.txt
           pip install coverage pytest-cov codecov

      - save_cache:
          paths:
            - ./venv
          key: >-
            v1-dependencies-{{ checksum "PyDynamic/requirements.txt" }}
            {{ checksum "agentMet4FoF/requirements.txt" }}

      # Run tests with coverage report and upload results to Codecov! We use
      # pytest's test-runner (https://pytest.org)
      - run:
          name: Run PyDynamic tests
          command: |
            . venv/bin/activate
            pytest -v --cov-config=PyDynamic/.coveragerc --cov=PyDynamic/ \
            PyDynamic/ > test-reports/PyDynamic.log
            codecov

      # Since there are no tests yet, we wait for them to uncomment this.
      #- run:
      #    name: Run agentMet4FoF tests
      #    command: |
      #      . venv/bin/activate
      #      pytest -v --cov=agentMet4FoF/ agentMet4FoF/ > \
      #      test-reports/agentMet4FoF.log
      #      codecov

      # Store test results.
      - store_artifacts:
         path: test-reports
         destination: test-reports

      - store_test_results:
         path: test-reports
